name: Deployment pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - name: Test and build app
        run: |
          cd test-project
          npm install
          npm run build
        id: build
      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./test-project/build